default: &default
  twitter_consumer_key: HAPKf0AkurnUPDLu2IDm1qsX9
  twitter_consumer_secret: rSBUbt4mJfpsMuZPu2RmvJE3NYSpt9VLeELiat9DFIY0SVbqp9
  geo_planet_app_id: 3LUU3WLV34FY0rX_BWcVtmdTlXD7SCV0qNpNeFbHaEKHtgeqGdoXnGVJ.MBZzFI-

development:
  <<: *default
  secret_key_base: f81082ca1921509b1df3e061a58de81210c6767b36ea68ec34024c9e40d2f8198e8937df8353340c7fe1e1f2c0254811560fa948f6f8b031d60ad320c081e714

test:
  <<: *default
  secret_key_base: ee3e8aad39f3b0b2600fed1d68c95e6b76c1783061bcb455023ddac701b3911060f3fa0beebd1fb8d2c2911c5ed52af3976641425478e0e6a8984f127789ca3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
